added contributing.md
Real-Dev-Squad/identity-service pull request #13
Opened 2021-12-26 18:51 UTC by lakshayman

2021-12-26 18:54 UTC, ankushdharkar requested changes

2021-12-26 18:54 UTC, ankushdharkar commented on CONTRIBUTING.md
> +Perform the tasks you wanted to, can be anything, ranging from fixing simple typo to re-designing the whole page!
Are we building any UI in this repo?

2021-12-28 12:41 UTC, rohan09-raj commented on CONTRIBUTING.md
> +Wait for it to get reviewed, make the changes required (if any) , commit your changes and hit **Pull Request** again, your commits will be added to the same pull request you had opened earlier (if it
Here, instead of commit and pull request, you can add steps of commit and push or just mention which steps to repeat.

2021-12-28 12:58 UTC, rohan09-raj requested changes

2021-12-28 12:58 UTC, rohan09-raj commented on CONTRIBUTING.md
> +Wait for it to get reviewed, make the changes required (if any) , commit your changes and push the changes again in you forked repository as mentioned in **Step 7** and **Step 10**, your commits will
Typo `you` -> `your`

2021-12-28 13:01 UTC, lakshayman commented on CONTRIBUTING.md
> +Wait for it to get reviewed, make the changes required (if any) , commit your changes and push the changes again in you forked repository as mentioned in **Step 7** and **Step 10**, your commits will
Sorry😅
Corrected

2021-12-28 13:03 UTC, rohan09-raj approved these changes

2021-12-28 17:55 UTC, ankushdharkar approved these changes

2021-12-28 17:55 UTC, merged